"""
Plan Loop — Data Models.

Constitution compliance:
  - Principle II: Explicit Over Implicit (declared intent per step)
  - Principle IV: Composability Through Standards (atomic structures)
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from pathlib import Path
from typing import Optional


class PlanStatus(str, Enum):
    PENDING    = "pending"
    IN_PROGRESS = "in_progress"
    DONE       = "done"
    BLOCKED    = "blocked"


class StepPriority(str, Enum):
    HIGH   = "high"
    MEDIUM = "medium"
    LOW    = "low"


@dataclass
class PlanStep:
    """One actionable step inside a Plan."""
    id: str
    title: str
    description: str = ""
    priority: StepPriority = StepPriority.MEDIUM
    depends_on: list[str] = field(default_factory=list)
    estimated_minutes: int = 30
    assignee: str = "ai-employee"

    def to_markdown(self) -> str:
        deps = f"\n  - depends_on: {', '.join(self.depends_on)}" if self.depends_on else ""
        return (
            f"### Step {self.id}: {self.title}\n"
            f"- **Priority**: {self.priority.value}\n"
            f"- **Estimate**: {self.estimated_minutes} min\n"
            f"- **Assignee**: {self.assignee}{deps}\n\n"
            f"{self.description}\n"
        )


@dataclass
class PlanItem:
    """An inbox item that needs a plan generated."""
    source_path: Path
    title: str
    content: str
    received_at: datetime = field(default_factory=lambda: datetime.now(tz=timezone.utc))
    tags: list[str] = field(default_factory=list)


@dataclass
class PlanDocument:
    """A complete Plan.md document to be written to the vault."""
    plan_id: str = field(default_factory=lambda: f"PLAN-{uuid.uuid4().hex[:8].upper()}")
    title: str = ""
    source_item: Optional[PlanItem] = None
    steps: list[PlanStep] = field(default_factory=list)
    context: str = ""
    goal: str = ""
    created_at: datetime = field(default_factory=lambda: datetime.now(tz=timezone.utc))
    status: PlanStatus = PlanStatus.PENDING
    tags: list[str] = field(default_factory=list)

    def to_markdown(self) -> str:
        date_str = self.created_at.strftime("%Y-%m-%d")
        time_str = self.created_at.strftime("%H:%M:%S UTC")
        tags_str = ", ".join(self.tags) if self.tags else "plan, ai-generated"
        steps_md = "\n".join(s.to_markdown() for s in self.steps)

        return (
            f"---\n"
            f"id: {self.plan_id}\n"
            f"title: {self.title}\n"
            f"status: {self.status.value}\n"
            f"created: {date_str}T{time_str}\n"
            f"tags: [{tags_str}]\n"
            f"---\n\n"
            f"# {self.title}\n\n"
            f"**Plan ID**: {self.plan_id}  \n"
            f"**Created**: {date_str} {time_str}  \n"
            f"**Status**: {self.status.value}  \n\n"
            f"---\n\n"
            f"## Goal\n\n{self.goal}\n\n"
            f"---\n\n"
            f"## Context\n\n{self.context}\n\n"
            f"---\n\n"
            f"## Steps\n\n{steps_md}\n"
            f"---\n\n"
            f"*Auto-generated by AI Employee Plan Loop — {date_str}*\n"
        )
