"""
BRONZE TIER — Filesystem Watcher
=================================
Monitors obsidian-vault/Inbox/ for new files.
When a file is dropped, creates a Needs_Action .md file and logs the event.

Document requirement: "One working Watcher script (file system monitoring)"

Usage:
    python watcher_fs.py                        # default vault path
    python watcher_fs.py --vault obsidian-vault # explicit path
    python watcher_fs.py --once                 # single scan (for testing)
    python watcher_fs.py --demo                 # drop a test file and watch it get processed

Architecture:
    Inbox/ (drop zone) → Watcher detects → Needs_Action/<name>.md created
    → 70-LOGS/watcher/<date>.jsonl updated → Dashboard.md updated
"""

from __future__ import annotations

import argparse
import json
import logging
import shutil
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

from watchdog.events import FileSystemEvent, FileSystemEventHandler
from watchdog.observers import Observer

# ---------------------------------------------------------------------------
# Logging setup
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s — %(message)s",
    datefmt="%Y-%m-%dT%H:%M:%S",
)
log = logging.getLogger("FilesystemWatcher")


# ---------------------------------------------------------------------------
# Vault paths helper
# ---------------------------------------------------------------------------
class VaultPaths:
    def __init__(self, vault_root: str | Path) -> None:
        self.root            = Path(vault_root).resolve()
        self.inbox           = self.root / "Inbox"
        self.needs_action    = self.root / "Needs_Action"
        self.done            = self.root / "Done"
        self.plans           = self.root / "Plans"
        self.pending_approval = self.root / "Pending_Approval"
        self.logs_dir        = self.root / "70-LOGS" / "watcher"
        self.dashboard       = self.root / "Dashboard.md"

    def ensure(self) -> None:
        """Create all required folders if they don't exist."""
        for folder in (
            self.inbox, self.needs_action, self.done,
            self.plans, self.pending_approval, self.logs_dir,
        ):
            folder.mkdir(parents=True, exist_ok=True)


# ---------------------------------------------------------------------------
# Action file creator
# ---------------------------------------------------------------------------
def create_action_file(source: Path, vault: VaultPaths) -> Path:
    """
    Given a file dropped into Inbox, create a Needs_Action .md file.
    Returns the path of the created action file.
    """
    now      = datetime.now(timezone.utc)
    iso_ts   = now.strftime("%Y-%m-%dT%H:%M:%SZ")
    date_str = now.strftime("%Y-%m-%d")
    time_str = now.strftime("%H%M%S")

    # Build a safe filename for the action item
    safe_name  = "".join(c if c.isalnum() or c in "-_." else "_" for c in source.name)
    action_name = f"FILE_{date_str}_{time_str}_{safe_name}.md"
    action_path = vault.needs_action / action_name

    # Determine file size
    try:
        size_bytes = source.stat().st_size
        size_str   = f"{size_bytes:,} bytes"
    except Exception:
        size_str = "unknown"

    content = f"""---
type: file_drop
original_name: {source.name}
source_path: {source}
size: {size_str}
received: {iso_ts}
status: pending
tier: 1
---

# Action Required: New File Detected

A new file has been dropped into the **Inbox** and is ready for processing.

## File Details

| Field         | Value                    |
|---------------|--------------------------|
| Name          | `{source.name}`          |
| Size          | {size_str}               |
| Received      | {iso_ts}                 |
| Source        | Inbox/                   |
| Tier          | 1 (Low-Risk — auto-log)  |

## Suggested Actions

- [ ] Review file contents
- [ ] Determine if action is needed
- [ ] Move to `/Done` when complete
- [ ] If sensitive, move to `/Pending_Approval`

## Processing Notes

_Add notes here as you process this item._

---
*Auto-generated by FilesystemWatcher (Bronze Tier) — {iso_ts}*
"""

    action_path.write_text(content, encoding="utf-8")
    log.info("Created action file: %s", action_path.name)
    return action_path


# ---------------------------------------------------------------------------
# JSONL audit logger
# ---------------------------------------------------------------------------
def log_event(vault: VaultPaths, event_type: str, source_file: str,
              action_file: str = "") -> None:
    """Append one JSONL line to 70-LOGS/watcher/<date>.jsonl"""
    date_str  = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    log_path  = vault.logs_dir / f"{date_str}.jsonl"
    entry = {
        "timestamp":   datetime.now(timezone.utc).isoformat(),
        "event_type":  event_type,
        "actor":       "filesystem_watcher",
        "source_file": source_file,
        "action_file": action_file,
        "vault":       str(vault.root),
    }
    with log_path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(entry) + "\n")


# ---------------------------------------------------------------------------
# Watchdog event handler
# ---------------------------------------------------------------------------
class InboxHandler(FileSystemEventHandler):
    """Handles file creation events inside obsidian-vault/Inbox/."""

    def __init__(self, vault: VaultPaths) -> None:
        super().__init__()
        self._vault = vault
        self._processed: set[str] = set()

    def on_created(self, event: FileSystemEvent) -> None:
        if event.is_directory:
            return

        src = Path(event.src_path)

        # Skip hidden, temp, and README files
        if src.name.startswith((".", "~")) or src.name in ("README.md",):
            return

        # Skip if already processed (watchdog can fire twice)
        if str(src) in self._processed:
            return
        self._processed.add(str(src))

        log.info("New file detected in Inbox: %s", src.name)

        try:
            action_path = create_action_file(src, self._vault)
            log_event(
                self._vault,
                event_type="file_drop",
                source_file=src.name,
                action_file=action_path.name,
            )
            print(f"\n{'='*60}")
            print(f"  [WATCHER] New file detected!")
            print(f"  Source  : Inbox/{src.name}")
            print(f"  Action  : Needs_Action/{action_path.name}")
            print(f"  Status  : PENDING (Tier 1 — logged)")
            print(f"{'='*60}\n")
        except Exception as exc:
            log.error("Failed to process %s: %s", src.name, exc)
            log_event(self._vault, "error", src.name)


# ---------------------------------------------------------------------------
# Single scan (--once mode)
# ---------------------------------------------------------------------------
def scan_once(vault: VaultPaths) -> int:
    """Process any existing files in Inbox (non-continuous mode)."""
    files = [
        f for f in vault.inbox.iterdir()
        if f.is_file() and not f.name.startswith(".") and f.name != "README.md"
    ]
    if not files:
        print("Inbox is empty — nothing to process.")
        return 0

    print(f"Found {len(files)} file(s) in Inbox:")
    for src in files:
        action_path = create_action_file(src, vault)
        log_event(vault, "file_drop", src.name, action_path.name)
        print(f"  {src.name} → Needs_Action/{action_path.name}")
    return len(files)


# ---------------------------------------------------------------------------
# Demo mode: drop a test file, then watch it get processed
# ---------------------------------------------------------------------------
def run_demo(vault: VaultPaths) -> None:
    """Create a test file in Inbox and let the watcher process it."""
    test_file = vault.inbox / f"test_invoice_{datetime.now().strftime('%H%M%S')}.txt"
    test_file.write_text(
        "Client: Acme Corp\nAmount: $500\nDue: 2026-03-10\nInvoice: #1234\n",
        encoding="utf-8",
    )
    print(f"\n[DEMO] Dropped test file: {test_file.name}")
    print("[DEMO] Processing via scan_once ...\n")
    scan_once(vault)
    print("\n[DEMO] Check obsidian-vault/Needs_Action/ to see the generated action item.")


# ---------------------------------------------------------------------------
# Continuous watcher (default mode)
# ---------------------------------------------------------------------------
def run_continuous(vault: VaultPaths) -> None:
    handler  = InboxHandler(vault)
    observer = Observer()
    observer.schedule(handler, str(vault.inbox), recursive=False)
    observer.start()

    print(f"\n{'='*60}")
    print("  PERSONAL AI EMPLOYEE — Filesystem Watcher")
    print(f"  Watching: {vault.inbox}")
    print("  Drop any file into Inbox/ to trigger processing.")
    print("  Press Ctrl+C to stop.")
    print(f"{'='*60}\n")

    log.info("Watcher started. Monitoring: %s", vault.inbox)
    log_event(vault, "watcher_start", "")

    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        log.info("Stopping watcher (Ctrl+C).")
    finally:
        observer.stop()
        observer.join()
        log_event(vault, "watcher_stop", "")
        print("\nWatcher stopped. Bye!")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
def main() -> None:
    parser = argparse.ArgumentParser(
        prog="watcher_fs",
        description="Bronze Tier — Filesystem Watcher for Personal AI Employee",
    )
    parser.add_argument(
        "--vault", default="obsidian-vault",
        help="Path to Obsidian vault root (default: obsidian-vault)",
    )
    parser.add_argument(
        "--once", action="store_true",
        help="Scan Inbox once and exit (no continuous monitoring)",
    )
    parser.add_argument(
        "--demo", action="store_true",
        help="Drop a test file into Inbox and process it (for demonstration)",
    )
    args = parser.parse_args()

    vault = VaultPaths(args.vault)
    vault.ensure()

    if args.demo:
        run_demo(vault)
    elif args.once:
        count = scan_once(vault)
        sys.exit(0 if count >= 0 else 1)
    else:
        run_continuous(vault)


if __name__ == "__main__":
    main()
