"""
RALPH_WIGGUM_LOOP_SKILL — Status Reporter
Writes loop status summaries to the vault so the human operator
can see what's happening at a glance.

Output files:
  80-MEMORY/loop-status.md          — always-current status (overwritten each tick)
  70-LOGS/ralph/daily/YYYY-MM-DD.md — append-only daily log
"""

from __future__ import annotations

import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from .models import HealthState, LoopState, TickResult, TickStatus


class StatusReporter:
    """
    Writes human-readable status to the vault after each tick.

    Files written:
    - ``80-MEMORY/loop-status.md``   (overwritten; always reflects latest)
    - ``70-LOGS/ralph/daily/YYYY-MM-DD.md`` (appended)
    """

    _STATUS_FILE = Path("80-MEMORY") / "loop-status.md"
    _DAILY_ROOT  = Path("70-LOGS") / "ralph" / "daily"

    def __init__(self, vault_root: str | Path) -> None:
        self._vault      = Path(vault_root)
        self._status_file = self._vault / self._STATUS_FILE
        self._daily_dir  = self._vault / self._DAILY_ROOT
        self._daily_dir.mkdir(parents=True, exist_ok=True)
        self._status_file.parent.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------------

    def report(
        self,
        tick: TickResult,
        state: LoopState,
        pending_tasks: int = 0,
        memory_stats: Optional[dict] = None,
    ) -> None:
        """Write status after a completed tick. Never raises."""
        try:
            self._write_status(tick, state, pending_tasks, memory_stats)
            self._append_daily(tick, state, pending_tasks)
        except Exception as exc:  # noqa: BLE001
            print(f"[StatusReporter] write failed: {exc}", file=sys.stderr)

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    def _write_status(
        self,
        tick: TickResult,
        state: LoopState,
        pending_tasks: int,
        memory_stats: Optional[dict],
    ) -> None:
        now = datetime.now(tz=timezone.utc)
        icon = self._tick_icon(tick.status)
        health_line = ""
        if tick.health:
            hi = "🟢" if tick.health.overall == HealthState.HEALTHY else (
                 "🟡" if tick.health.overall == HealthState.DEGRADED else "🔴")
            health_line = (
                f"- **Health**: {hi} {tick.health.overall.value}  "
                f"({tick.health.healthy_count}/{len(tick.health.components)} healthy)\n"
            )

        uptime_pct = (
            f"{state.uptime_ticks / state.tick_count * 100:.1f}%"
            if state.tick_count else "n/a"
        )

        mem_line = ""
        if memory_stats:
            mem_line = (
                f"- **Memory**: {memory_stats.get('consolidated_count', 0)} entries consolidated "
                f"({memory_stats.get('skipped_count', 0)} skipped)\n"
            )

        phase_lines = "\n".join(
            f"  - `{p.phase}` → {p.status.value} ({p.duration_ms:.0f}ms)"
            + (f" — {p.error[:80]}" if p.error else "")
            for p in tick.phase_results
        )

        content = (
            f"# Ralph Wiggum Loop — Status\n\n"
            f"*Updated: {now.strftime('%Y-%m-%dT%H:%M:%SZ')}*\n\n"
            f"---\n\n"
            f"## Latest Tick {icon}\n\n"
            f"- **Tick**: #{tick.tick_number} (`{tick.tick_id}`)\n"
            f"- **Status**: `{tick.status.value}`\n"
            f"- **Duration**: {tick.duration_ms:.0f}ms\n"
            f"{health_line}"
            f"\n### Phase Results\n\n{phase_lines or '  (none)'}\n\n"
            f"---\n\n"
            f"## Loop Stats\n\n"
            f"- **Total ticks**: {state.tick_count}\n"
            f"- **Uptime**: {uptime_pct} ({state.uptime_ticks} successful)\n"
            f"- **Consecutive fails**: {state.consecutive_fails}\n"
            f"- **Pending tasks**: {pending_tasks}\n"
            f"- **Total tasks done**: {state.total_tasks_done}\n"
            f"{mem_line}"
            f"\n---\n\n"
            f"*Generated by RALPH_WIGGUM_LOOP_SKILL v1.0.0*\n"
        )
        self._status_file.write_text(content, encoding="utf-8")

    def _append_daily(
        self, tick: TickResult, state: LoopState, pending_tasks: int
    ) -> None:
        now  = datetime.now(tz=timezone.utc)
        date = now.strftime("%Y-%m-%d")
        path = self._daily_dir / f"{date}.md"

        # Header (written once per day)
        if not path.exists():
            path.write_text(
                f"# Ralph Daily Log — {date}\n\n"
                f"| Time | Tick | Status | Duration | Tasks Pending | Consecutive Fails |\n"
                f"|------|------|--------|----------|---------------|------------------|\n",
                encoding="utf-8",
            )

        ts = now.strftime("%H:%M:%SZ")
        with path.open("a", encoding="utf-8") as fh:
            fh.write(
                f"| {ts} | #{tick.tick_number} `{tick.tick_id}` "
                f"| {tick.status.value} | {tick.duration_ms:.0f}ms "
                f"| {pending_tasks} | {state.consecutive_fails} |\n"
            )

    @staticmethod
    def _tick_icon(status: TickStatus) -> str:
        return {"success": "✅", "partial": "⚠️", "failed": "❌", "skipped": "⏭️"}.get(
            status.value, "❓"
        )
