"""
FILESYSTEM_AUTOMATION_SKILL — Logger
Phase 1: Structured logging to obsidian-vault/70-LOGS/.

Log levels: INFO | WARN | ERROR
Daily log file: 70-LOGS/daily/YYYY-MM-DD.md
Error log file: 70-LOGS/errors/YYYY-MM-DD.md

Constitution compliance:
  - Principle VI: Fail Safe, Fail Visible
  - Section 7: Logging Requirements
"""

import os
from datetime import datetime, timezone
from pathlib import Path


class SkillLogger:
    """
    Appends structured log entries to markdown files inside 70-LOGS/.

    Format (each entry):
        <!-- LOG | LEVEL | TIMESTAMP -->
        <message>

    Never raises on write failures — it prints a stderr warning instead
    so that a logging bug cannot crash the primary operation.
    """

    def __init__(self, vault_root: str | Path) -> None:
        self.vault_root = Path(vault_root).resolve()
        self._daily_dir  = self.vault_root / "70-LOGS" / "daily"
        self._error_dir  = self.vault_root / "70-LOGS" / "errors"
        self._ops_dir    = self.vault_root / "70-LOGS" / "operations"
        self._ensure_dirs()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def info(self, message: str, *, context: dict | None = None) -> None:
        """Log an INFO-level event to the daily log."""
        self._write(self._daily_log_path(), "INFO", message, context)

    def warn(self, message: str, *, context: dict | None = None) -> None:
        """Log a WARN-level event to the daily log."""
        self._write(self._daily_log_path(), "WARN", message, context)

    def error(self, message: str, *, context: dict | None = None) -> None:
        """Log an ERROR-level event to both the daily log and error log."""
        ts = self._now()
        self._write(self._daily_log_path(ts), "ERROR", message, context, ts)
        self._write(self._error_log_path(ts), "ERROR", message, context, ts)

    def audit(self, operation: str, details: dict) -> None:
        """
        Append a structured audit entry to 70-LOGS/operations/YYYY-MM-DD.md.

        *details* should contain file_before, file_after, result, duration_ms, etc.
        """
        ts = self._now()
        path = self._ops_dir / f"{ts.strftime('%Y-%m-%d')}.md"
        lines = [
            f"\n## {operation} — {ts.isoformat()}",
            "```yaml",
        ]
        for k, v in details.items():
            lines.append(f"{k}: {v}")
        lines.append("```\n")
        self._append(path, "\n".join(lines))

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _now(self) -> datetime:
        return datetime.now(tz=timezone.utc)

    def _daily_log_path(self, ts: datetime | None = None) -> Path:
        if ts is None:
            ts = self._now()
        return self._daily_dir / f"{ts.strftime('%Y-%m-%d')}.md"

    def _error_log_path(self, ts: datetime | None = None) -> Path:
        if ts is None:
            ts = self._now()
        return self._error_dir / f"{ts.strftime('%Y-%m-%d')}.md"

    def _ensure_dirs(self) -> None:
        for d in (self._daily_dir, self._error_dir, self._ops_dir):
            try:
                d.mkdir(parents=True, exist_ok=True)
            except OSError:
                pass  # Fail-safe: continue even if dir creation fails

    def _write(
        self,
        path: Path,
        level: str,
        message: str,
        context: dict | None,
        ts: datetime | None = None,
    ) -> None:
        if ts is None:
            ts = self._now()
        iso = ts.strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"
        ctx_str = ""
        if context:
            ctx_str = " | " + " | ".join(f"{k}={v}" for k, v in context.items())
        entry = f"- `{level}` [{iso}] {message}{ctx_str}\n"
        self._append(path, entry)

    def _append(self, path: Path, content: str) -> None:
        try:
            # Create file with header if it doesn't exist
            if not path.exists():
                header = (
                    f"# Filesystem Automation Log — {path.stem}\n\n"
                    "_Generated by FILESYSTEM_AUTOMATION_SKILL v1.0.0_\n\n"
                )
                path.write_text(header, encoding="utf-8")
            with path.open("a", encoding="utf-8") as f:
                f.write(content)
        except OSError as exc:
            import sys
            print(f"[SKILL LOGGER WARNING] Failed to write to {path}: {exc}", file=sys.stderr)
